language: c
sudo: required
install: test -e .travis-opam.sh || wget https://raw.githubusercontent.com/ocaml/ocaml-ci-scripts/master/.travis-opam.sh
script: bash -ex .travis-opam.sh
env:
  global:
    - PACKAGE=petr4
    - PRE_INSTALL_HOOK="make test; make test-stf"
  matrix:
    - OCAML_VERSION=4.09
    - OCAML_VERSION=4.10.0+beta1 OCAML_BETA=enable
    - OCAML_VERSION=4.10
os:
  - linux
  - osx
  - freebsd
